import manifestJson from "../../../public/models/manifest.json";

/**
 * Deck metadata + atlas geometry. Generated by tools/build_deck.py — do not
 * hand-edit the JSON.
 *
 * It is imported rather than fetched on purpose: the deck cannot lay itself out
 * until it knows how many cards there are, and a fetch would put a round trip in
 * front of the very first frame of the hero.
 */

export interface Atlas {
  src: string;
  /** null when the build ran without ffmpeg — callers must fall back to `src`. */
  srcAvif: string | null;
  width: number;
  height: number;
  cols: number;
  rows: number;
  tile: [number, number];
  maxTextureSize: number;
  bytes: number;
  bytesWebp: number;
}

export interface TarotCard {
  id: string;
  /** Place in the full 78-card deck. Does NOT address an atlas tile. */
  index: number;
  name: string;
  arcana: string | null;
  suit: string | null;
  number: string | null;
  keywords: string[];
  essence: string;
  /**
   * Slot in the atlas sheet, or null for a card the hero never spreads. The
   * sheet holds only the 22 the hero draws, so this is the only index `uvRect`
   * may be given — `index` addressed a tile back when all 78 were packed, and
   * passing it now samples the wrong art with no type error to stop you.
   */
  atlasIndex: number | null;
}

/** A card that has a tile, i.e. one the hero can actually render. */
export interface HeroCard extends TarotCard {
  atlasIndex: number;
}

interface Manifest {
  model: string;
  back: string;
  backAvif: string | null;
  cardSize: [number, number, number];
  heroCount: number;
  atlases: Atlas[];
  cards: TarotCard[];
}

export const MANIFEST = manifestJson as unknown as Manifest;

export const CARDS = MANIFEST.cards;
export const CARD_MODEL = MANIFEST.model;
export const BACK_TEXTURE = MANIFEST.back;

/** World units: 1.0 x 1.714 x 0.005 — see tools/card_mesh.py. */
export const [CARD_W, CARD_H, CARD_T] = MANIFEST.cardSize;

/**
 * The 22 Major Arcana, in trump order (The Fool -> The World).
 *
 * The deck holds all 78 but the hero spreads only the trumps: across a single
 * screen 78 cards overlap to a ~12% sliver each, which neither showcases the
 * art nor leaves a hoverable target.
 *
 * The atlas is packed from exactly this subset, which is what paid for the
 * tiles to go up to the masters' native 350x600 — 22 fit under the 4096 limit
 * at full resolution where 78 had to be downsampled to 256x440. So this is
 * derived from the sheet rather than re-filtering on arcana: a card with no
 * atlasIndex has no tile, and the two cannot drift apart. To spread the full
 * deck, change HERO_ARCANA in tools/build_deck.py and rebuild — the grids there
 * have to grow with it.
 */
export const HERO_CARDS: HeroCard[] = CARDS.filter(
  (c): c is HeroCard => c.atlasIndex !== null,
).sort((a, b) => a.atlasIndex - b.atlasIndex);

/**
 * The mobile fan, sampled evenly across the trumps (The Fool -> The World).
 *
 * Seven, not twenty-two: a fan wide enough to fit a 375px screen splits 22 cards
 * into ~13px slivers, which is a third of a usable touch target. Seven leaves
 * each card a ~50px wedge at the tip, where a thumb actually lands.
 */
const MOBILE_COUNT = 7;

export const MOBILE_CARDS: HeroCard[] = Array.from(
  { length: MOBILE_COUNT },
  (_, i) =>
    HERO_CARDS[Math.round((i * (HERO_CARDS.length - 1)) / (MOBILE_COUNT - 1))],
);

/** The spread for a viewport. Both the deck and the overlay resolve it. */
export const heroCards = (isMobile: boolean): HeroCard[] =>
  isMobile ? MOBILE_CARDS : HERO_CARDS;

export const byId = (id: string) => CARDS.find((c) => c.id === id);

/**
 * The card's rect inside an atlas sheet, as [offsetU, offsetV, scaleU, scaleV].
 *
 * `index` here is a card's `atlasIndex` — its slot in the sheet — not its place
 * in the 78-card deck. The two were the same number until the atlas stopped
 * carrying the 56 cards the hero never draws.
 *
 * Row 0 is the TOP row and V grows downward, which only holds because the atlas
 * is sampled with `flipY = false` (the glTF convention, see useDeckTexture).
 * tools/verify_deck.py re-derives tiles with this exact arithmetic, so the two
 * must be changed together.
 */
export function uvRect(
  atlas: Atlas,
  index: number,
): [number, number, number, number] {
  const [tw, th] = atlas.tile;
  return [
    ((index % atlas.cols) * tw) / atlas.width,
    (Math.floor(index / atlas.cols) * th) / atlas.height,
    tw / atlas.width,
    th / atlas.height,
  ];
}

/**
 * Best atlas the device can actually sample. Sheets are NPOT, so mipmapping
 * them needs WebGL2 — universal in practice, but the smaller sheet is also the
 * safest fallback and a third of the bytes.
 */
export function pickAtlas(maxTextureSize: number): Atlas {
  const fits = MANIFEST.atlases.filter((a) => a.maxTextureSize <= maxTextureSize);
  const usable = fits.length ? fits : MANIFEST.atlases;
  return usable.reduce((best, a) =>
    a.maxTextureSize > best.maxTextureSize ? a : best,
  );
}

/**
 * The sheet all but the most limited GPUs resolve to, so it is the one worth
 * preloading from the document head (layout.tsx).
 *
 * Routed through pickAtlas rather than reading atlases[0] on purpose: this has
 * to agree with the runtime choice exactly. A preload for a URL the deck then
 * declines to use is not a no-op — it is a megabyte fetched twice.
 */
export const TOP_ATLAS = pickAtlas(Number.POSITIVE_INFINITY);

/**
 * Every sheet ships as AVIF (~37% smaller) with a WebP twin. Support cannot be
 * probed synchronously, so the probe is a module-level promise: it starts the
 * moment this module is imported and has settled long before the R3F canvas
 * mounts. `useDeckTexture` suspends on it inside the Suspense boundary that
 * `useLoader` already needs, so it costs no extra round trip.
 *
 * Guessing wrong is not a graceful degradation — a browser that cannot decode
 * AVIF draws 78 black cards — so this decodes an actual AVIF rather than
 * sniffing the user agent.
 */
const AVIF_PROBE =
  "data:image/avif;base64,AAAAIGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZk1BMUIAAAD5bWV0YQAAAAAA" +
  "AAAvaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAFBpY3R1cmVIYW5kbGVyAAAAAA5waXRtAAAAAAABAAAA" +
  "Hmlsb2MAAAAARAAAAQABAAAAAQAAASEAAAAUAAAAKGlpbmYAAAAAAAEAAAAaaW5mZQIAAAAAAQAAYXYwMUNv" +
  "bG9yAAAAAGppcHJwAAAAS2lwY28AAAAUaXNwZQAAAAAAAAACAAAAAgAAABBwaXhpAAAAAAMICAgAAAAMYXYx" +
  "Q4EADAAAAAATY29scm5jbHgAAgACAAIAAAAAF2lwbWEAAAAAAAAAAQABBAECgwQAAAAcbWRhdAoFGAA2wCAy" +
  "Cx/wAABYAAAAAK8w";

export const avifSupported: Promise<boolean> =
  typeof Image === "undefined"
    ? Promise.resolve(false) // SSR: the deck only ever loads in the browser
    : new Promise((resolve) => {
        const img = new Image();
        img.onload = () => resolve(img.width === 2);
        img.onerror = () => resolve(false);
        img.src = AVIF_PROBE;
      });

/** AVIF twin when the browser can decode it and the build produced one. */
export function preferAvif(webp: string, avif: string | null, ok: boolean) {
  return ok && avif ? avif : webp;
}
